{
  "user": null,
  "success": true,
  "data": [
    {
      "id": 187,
      "apdId": "A004",
      "productName": "US Commercial Paper (USCP)",
      "qLProductName": null,
      "primaryDesk": "Money Market Desk",
      "productStatus": "",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 214,
      "apdId": "A009",
      "productName": "European Commercial Paper (ECP)",
      "qLProductName": null,
      "primaryDesk": "Money Market Desk",
      "productStatus": "",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Rohit",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 218,
      "apdId": "A031",
      "productName": "Enhanced Collar",
      "qLProductName": null,
      "primaryDesk": "Rates Desk",
      "productStatus": "",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 190,
      "apdId": "A072",
      "productName": "FX Spot",
      "qLProductName": null,
      "primaryDesk": "FX Spot Desk",
      "productStatus": "",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 236,
      "apdId": "A075",
      "productName": "European Currency Options",
      "qLProductName": null,
      "primaryDesk": "FX Options Desk",
      "productStatus": "",
      "auditStatus": "Initiated",
      "auditUser": "Rohit",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 237,
      "apdId": "A131",
      "productName": "devv09 testing",
      "qLProductName": "Averaging CapFloor",
      "primaryDesk": "Rates Desk",
      "productStatus": "Withdrawn",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Rohit",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 237,
      "apdId": "A131",
      "productName": "devv09 testing",
      "qLProductName": "Bond",
      "primaryDesk": "Rates Desk",
      "productStatus": "Withdrawn",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Rohit",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 237,
      "apdId": "A131",
      "productName": "devv09 testing",
      "qLProductName": "Bond Contract for Difference",
      "primaryDesk": "Rates Desk",
      "productStatus": "Withdrawn",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Rohit",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 237,
      "apdId": "A131",
      "productName": "devv09 testing",
      "qLProductName": "Bond Corporate",
      "primaryDesk": "Rates Desk",
      "productStatus": "Withdrawn",
      "auditStatus": "Pending Confirmation",
      "auditUser": "Rohit",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 203,
      "apdId": "A133",
      "productName": "test100",
      "qLProductName": null,
      "primaryDesk": "Commodities Desk",
      "productStatus": "Active",
      "auditStatus": "Initiated",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 210,
      "apdId": "A134",
      "productName": "boom",
      "qLProductName": null,
      "primaryDesk": "Commodities Desk",
      "productStatus": null,
      "auditStatus": "Pending Confirmation",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 233,
      "apdId": "A142",
      "productName": "landing pagetest",
      "qLProductName": null,
      "primaryDesk": null,
      "productStatus": "",
      "auditStatus": "Initiated",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 234,
      "apdId": "A143",
      "productName": "test test test",
      "qLProductName": null,
      "primaryDesk": null,
      "productStatus": null,
      "auditStatus": "Initiated",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 235,
      "apdId": "A144",
      "productName": "cross test",
      "qLProductName": null,
      "primaryDesk": null,
      "productStatus": null,
      "auditStatus": "Initiated",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 241,
      "apdId": "A145",
      "productName": "qweqwe",
      "qLProductName": null,
      "primaryDesk": null,
      "productStatus": null,
      "auditStatus": "Initiated",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    },
    {
      "id": 242,
      "apdId": "A146",
      "productName": "qweqweqwe",
      "qLProductName": null,
      "primaryDesk": null,
      "productStatus": null,
      "auditStatus": "Initiated",
      "auditUser": "Guest",
      "grouping1": null,
      "grouping2": null,
      "approvedVersionExists": false
    }
  ],
  "errorMessages": []
}
