export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

 export const ACTION_VIEW = 'View'; 
 export const AUDIT_STATUS_PEND_CONFIRM = 'Confirm Pending'; 
 export const ACTION_EDIT = 'Edit'; 
 export const ACTION_CONFIRM = 'Confirm'; 

export const LOAD_INPROGRESS_PRODUCTS_SUCCESS = 'LOAD_INPROGRESS_PRODUCTS_SUCCESS';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const GET_PRODUCTS = 'GET_PRODUCTS';

